#!/usr/bin/env bash
# Reproducible alignment script for EETT eIDAS dossier
# Creates/aligns the target ASiC-E directory structure, maps sources, and creates placeholders for missing items.
# Also generates an alignment summary and a draft META-INF/manifest.xml with SHA-256 digests.
#
# Usage:
#   bash scripts/reproduce_alignment.sh [--dry-run] [--no-manifest]
#
# Notes:
# - This script is idempotent. Re-running it will overwrite files in the target dossier with current sources/placeholders.
# - Placeholders contain exactly: "PLACEHOLDER – to be replaced with official document"
# - The "mimetype" file is written with exact content (no trailing newline).
# - The manifest is a draft; regenerate for the final package and sign with XAdES-LTA as per your signing process.

set -euo pipefail

DRY_RUN=0
WITH_MANIFEST=1

for arg in "${@:-}"; do
  case "${arg}" in
    --dry-run) DRY_RUN=1 ;;
    --no-manifest) WITH_MANIFEST=0 ;;
    -h|--help)
      echo "Usage: $0 [--dry-run] [--no-manifest]"
      exit 0
      ;;
    *)
      echo "Unknown argument: ${arg}" >&2
      exit 1
      ;;
  esac
done

# Resolve repository paths relative to this script location
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${REPO_ROOT}"

TARGET_DIR="EETT_Dossier_GreekTrustCo_2025-06-15.asice"
ALIGN_LOG="${TARGET_DIR}/alignment.log"
ALIGN_SUMMARY="${TARGET_DIR}/ALIGNMENT_SUMMARY.md"

# Logging helpers
ts() { date +"%Y-%m-%dT%H:%M:%S%z"; }
log() { printf "[%s] %s\n" "$(ts)" "$*" | tee -a "${ALIGN_LOG}"; }
info() { log "INFO  $*"; }
warn() { log "WARN  $*"; }
error() { log "ERROR $*"; }

# DRY-RUN aware wrappers
do_mkdir() {
  local d="$1"
  if [[ "${DRY_RUN}" -eq 1 ]]; then
    info "DRY-RUN mkdir -p ${d}"
  else
    mkdir -p "${d}"
    info "mkdir -p ${d}"
  fi
}

do_write_file() {
  local path="$1"
  local content="$2"
  if [[ "${DRY_RUN}" -eq 1 ]]; then
    info "DRY-RUN write ${path}"
  else
    # shellcheck disable=SC2059
    printf "%s" "${content}" > "${path}"
    info "write ${path}"
  fi
}

do_copy() {
  local src="$1"
  local dest="$2"
  if [[ "${DRY_RUN}" -eq 1 ]]; then
    info "DRY-RUN cp -f ${src} ${dest}"
  else
    cp -f "${src}" "${dest}"
    info "cp -f ${src} ${dest}"
  fi
}

append_summary_row() {
  local status="$1" fname="$2" action="$3" notes="$4"
  if [[ "${DRY_RUN}" -eq 1 ]]; then
    info "DRY-RUN summary: ${status} | ${fname} | ${action} | ${notes}"
  else
    printf "| %s | %s | %s | %s |\n" "${status}" "${fname}" "${action}" "${notes}" >> "${ALIGN_SUMMARY}"
  fi
}

# Placeholder content: EXACTLY as per requirement
PLACEHOLDER_LINE="PLACEHOLDER – to be replaced with official document"

ensure_summary_header() {
  if [[ "${DRY_RUN}" -eq 1 ]]; then
    info "DRY-RUN initialize ALIGNMENT_SUMMARY.md"
    return
  fi
  cat > "${ALIGN_SUMMARY}" <<'EOF'
# Alignment Summary

Status | File Name | Action Taken | Notes
---|---|---|---
EOF
  info "initialized ${ALIGN_SUMMARY}"
}

# Create all required directories for target structure
bootstrap_directories() {
  do_mkdir "${TARGET_DIR}"
  do_mkdir "${TARGET_DIR}/META-INF"
  do_mkdir "${TARGET_DIR}/06_Test_Certificates"
  do_mkdir "${TARGET_DIR}/Supporting_Docs/Financial"
  do_mkdir "${TARGET_DIR}/Supporting_Docs/Certifications"
  do_mkdir "${TARGET_DIR}/Supporting_Docs/Legal/Director_IDs"
  do_mkdir "${TARGET_DIR}/Supporting_Docs/Personnel/Qualifications"
}

# Create the fixed-content mimetype file (no trailing newline)
ensure_mimetype() {
  local path="${TARGET_DIR}/mimetype"
  if [[ "${DRY_RUN}" -eq 1 ]]; then
    info "DRY-RUN write fixed mimetype"
  else
    # Write without newline to better match ASiC-E packaging expectations
    printf "application/vnd.etsi.asic-e+zip" > "${path}"
    info "wrote fixed mimetype"
  fi
  append_summary_row "✅" "mimetype" "Created/Updated" "Fixed content"
}

# Create META-INF templates (manifest and signatures placeholders)
ensure_meta_templates() {
  local manifest="${TARGET_DIR}/META-INF/manifest.xml"
  local signatures="${TARGET_DIR}/META-INF/signatures.xml"
  local asicmanifest="${TARGET_DIR}/META-INF/ASiCManifest.xml"

  # Minimal placeholder content; actual values will be regenerated below (if WITH_MANIFEST=1)
  if [[ "${DRY_RUN}" -eq 1 ]]; then
    info "DRY-RUN write META-INF templates"
  else
    cat > "${manifest}" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<asic:Manifest xmlns:asic="http://uri.etsi.org/02918/v1.2.1#" xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
  <!-- Draft manifest. Will be (re)generated by this script if --no-manifest is not used. -->
  <asic:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
</asic:Manifest>
EOF
    cat > "${signatures}" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<asic:ASiCSignatures xmlns:asic="http://uri.etsi.org/02918/v1.2.1#" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xades="http://uri.etsi.org/01903/v1.3.2#" xmlns:xades141="http://uri.etsi.org/01903/v1.4.1#">
  <!-- Placeholder – replace with XAdES-LTA signature at packaging time -->
</asic:ASiCSignatures>
EOF
    cat > "${asicmanifest}" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<asic:ASiCManifest xmlns:asic="http://uri.etsi.org/02918/v1.2.1#" xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
  <!-- Optional metadata file; kept minimal here. -->
  <asic:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
</asic:ASiCManifest>
EOF
    info "wrote META-INF templates"
  fi

  append_summary_row "✅" "META-INF/manifest.xml" "Created/Updated" "Template"
  append_summary_row "✅" "META-INF/signatures.xml" "Created/Updated" "Placeholder"
  append_summary_row "✅" "META-INF/ASiCManifest.xml" "Created/Updated" "Optional"
}

# Compute sha256 hex digest; prefers sha256sum, falls back to shasum -a 256
sha256_hex() {
  local f="$1"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    echo "ERROR: Neither sha256sum nor shasum found" >&2
    return 1
  fi
}

# Convert hex to base64; requires xxd and base64
hex_to_base64() {
  local hex="$1"
  # shellcheck disable=SC2059
  printf "%s" "${hex}" | xxd -r -p | base64
}

# Generate a draft manifest enumerating all payload files (excluding META-INF/*)
generate_manifest() {
  local manifest="${TARGET_DIR}/META-INF/manifest.xml"
  [[ "${WITH_MANIFEST}" -eq 1 ]] || { warn "Skipping manifest generation (--no-manifest)"; return; }

  if ! command -v xxd >/dev/null 2>&1 || ! command -v base64 >/dev/null 2>&1; then
    warn "xxd/base64 not found; writing minimal manifest without entries"
    return
  fi

  local tmp="$(mktemp)"
  {
    echo '<?xml version="1.0" encoding="UTF-8"?>'
    echo '<asic:Manifest xmlns:asic="http://uri.etsi.org/02918/v1.2.1#" xmlns:ds="http://www.w3.org/2000/09/xmldsig#">'
    echo '  <asic:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>'
    # Iterate files, excluding META-INF/*
    while IFS= read -r -d '' f; do
      # URI relative to container root
      local_path="${f#${TARGET_DIR}/}"
      # Skip META-INF and directories
      if [[ "${local_path}" == META-INF/* ]]; then
        continue
      fi
      if [[ -f "${f}" ]]; then
        hex="$(sha256_hex "${f}")" || { warn "Failed sha256 for ${local_path}"; continue; }
        b64="$(hex_to_base64 "${hex}")"
        # XML entry
        printf '  <asic:DataObjectReference URI="%s">\n' "${local_path}"
        printf '    <ds:DigestValue>%s</ds:DigestValue>\n' "${b64}"
        printf '  </asic:DataObjectReference>\n'
      fi
    done < <(find "${TARGET_DIR}" -type f -print0 | sort -z)
    echo '</asic:Manifest>'
  } > "${tmp}"

  if [[ "${DRY_RUN}" -eq 1 ]]; then
    info "DRY-RUN generate manifest entries"
    rm -f "${tmp}"
  else
    mv "${tmp}" "${manifest}"
    info "generated META-INF/manifest.xml"
  fi
}

# Map or create placeholder for a single file
# Arguments:
#   $1 target path relative to TARGET_DIR
#   $2 source path relative to REPO_ROOT (can be "-" to force placeholder)
map_or_placeholder() {
  local target_rel="$1"
  local source_rel="$2"
  local target_path="${TARGET_DIR}/${target_rel}"
  local target_dir
  target_dir="$(dirname "${target_path}")"

  # Ensure parent directory exists
  do_mkdir "${target_dir}"

  if [[ "${source_rel}" != "-" && -f "${source_rel}" ]]; then
    do_copy "${source_rel}" "${target_path}"
    append_summary_row "📝" "${target_rel}" "Mapped from ${source_rel}" "Normalized"
  else
    do_write_file "${target_path}" "${PLACEHOLDER_LINE}"
    append_summary_row "⚠️" "${target_rel}" "Placeholder created" "Missing or not provided"
  fi
}

# Seed Supporting_Docs placeholders (no known sources in repo)
seed_supporting_placeholders() {
  map_or_placeholder "Supporting_Docs/Financial/Balance_Sheet_2024.pdf" "-"
  map_or_placeholder "Supporting_Docs/Financial/Insurance_Policy.pdf" "-"
  map_or_placeholder "Supporting_Docs/Certifications/ISO27001_Certificate.pdf" "-"
  map_or_placeholder "Supporting_Docs/Certifications/ISO9001_Certificate.pdf" "-"
  map_or_placeholder "Supporting_Docs/Certifications/Datacenter_Certification.pdf" "-"
  map_or_placeholder "Supporting_Docs/Certifications/HSM_FIPS_Certification.pdf" "-"
  map_or_placeholder "Supporting_Docs/Certifications/CAB_Accreditation_Certificate.pdf" "-"
  map_or_placeholder "Supporting_Docs/Legal/GEMH_Company_Registration.pdf" "-"
  map_or_placeholder "Supporting_Docs/Legal/AFM_Tax_Registration.pdf" "-"
  map_or_placeholder "Supporting_Docs/Legal/Articles_of_Association.pdf" "-"
  map_or_placeholder "Supporting_Docs/Legal/Director_IDs/CEO_ID_Card.pdf" "-"
  map_or_placeholder "Supporting_Docs/Legal/Director_IDs/QTS_Manager_ID_Card.pdf" "-"
  map_or_placeholder "Supporting_Docs/Personnel/DPO_Appointment_Letter.pdf" "-"
  map_or_placeholder "Supporting_Docs/Personnel/Qualifications/QTS_Manager_CV_Certifications.pdf" "-"
  map_or_placeholder "Supporting_Docs/Personnel/Qualifications/Crypto_Officer_Qualifications.pdf" "-"
  map_or_placeholder "Supporting_Docs/Personnel/Qualifications/RA_Operator_Training_Certificates.pdf" "-"
}

# Main alignment routine
main() {
  : > "${ALIGN_LOG}" || true
  ensure_summary_header
  bootstrap_directories
  ensure_mimetype
  ensure_meta_templates

  # Define mappings: target_rel|source_rel (relative to repo root). Use "-" to force placeholder.
  # Keep this list synchronized with the target structure specification.
  local mappings
  mappings="$(cat <<'MAP'
01_Registry_Application_GreekTrustCo_SIGNED.pdf|01_Registry/01_Registry_Application_[LEGAL_NAME_GR].docx.md
01a_Registry_Fee_Proof_300EUR.pdf|01_Registry/01a_Fee_Proof.pdf.md
01b_Change_Notification_Template_SIGNED.pdf|01_Registry/01b_Change_Notice_Template.md
02_EETT_Qualified_Service_Start_Application_SIGNED.pdf|02_Qualified_Service_Application/02_EETT_Qualified_Service_Start_Application.md
02a_Cover_Letter_Electronic_System_Access_SIGNED.pdf|-
03_Conformity_Assessment_Report_TUV_2025.pdf|-
03a_Traceability_Matrix.pdf|-
04_TSP_Policy_GR_EN_SIGNED.pdf|04_Policies/04_TSP_Policy_EN.docx.md
05_TSPS_Qualified_Services_GR_EN_SIGNED.pdf|05_Policies/05_TSPS_EN.docx.md
06_Test_Certificates/Root_CA_Certificate.pem|-
06_Test_Certificates/Issuing_CA_QES_Certificate.pem|05_Test_Certificates/samples/3_QWAC_Sample.cer
06_Test_Certificates/Issuing_CA_QSeal_Certificate.pem|05_Test_Certificates/samples/2_QSeal_Sample.cer
06_Test_Certificates/TSA_CA_Certificate.pem|-
06_Test_Certificates/Sample_QES_Certificate.pem|05_Test_Certificates/samples/1_QES_Natural_Person_Sample.cer
06_Test_Certificates/Sample_OCSP_Response.der|05_Test_Certificates/samples/4_OCSP_Response_Sample.ors
06_Test_Certificates/Sample_CRL.crl|05_Test_Certificates/samples/5_CRL_Sample.crl
06_Test_Certificates/Certificate_Profiles_Guide.pdf|05_Test_Certificates/Documentation/20_Certificate_Profiles_Guide.md
07_Risk_Assessment_GR_EN.pdf|06_Risk_Incident/07_Risk_Assessment_Report_GR.docx.md
07a_Incident_Response_Plan_GR_EN.pdf|06_Risk_Incident/07a_Incident_Response_Plan_GR.docx.md
07b_Incident_Report_Forms.pdf|06_Risk_Incident/07b_Incident_Forms_GR.xlsx.md
08_User_Notification_Templates_GR_EN.pdf|07_User_Notifications/08_User_Notification_Plan_GR_EN.docx.md
09_Service_Termination_Plan_GR_EN.pdf|08_Termination/09_Termination_Plan_GR_EN.docx.md
10_End_User_Agreement_GR_EN_SIGNED.pdf|09_Contracts/10_Standard_End_User_Agreement_GR_EN.docx.md
11_Revocation_SOP_GR_EN.pdf|10_Revocation_Status/11_Revocation_Status_SOP_GR.docx.md
11a_Revocation_Forms.pdf|10_Revocation_Status/11a_Web_Disclosure_Text_GR.md
12_Recordkeeping_Policy_GR_EN.pdf|11_Records_Access/12_Records_and_Access_Policy_GR.docx.md
13_EETT_Communication_Templates_GR.pdf|12_EETT_Communications/13_EETT_Notification_Templates_GR.docx.md
14_NTL_Publication_Datasheet.pdf|13_NTL/14_NTL_Publication_Datasheet.xlsx.md
17_Executive_Brief_GR_EN_SIGNED.pdf|00_EXECUTIVE_BRIEF.md
18_Gantt_Chart_Project_Timeline.pdf|-
19_Master_Compliance_Register.pdf|15_Compliance_Master/Master_Compliance_Register.xlsx.md
20_README_and_Placeholder_Table.zip|-
MAP
)"

  # Apply mappings
  while IFS='|' read -r target_rel source_rel; do
    [[ -z "${target_rel}" ]] && continue
    map_or_placeholder "${target_rel}" "${source_rel}"
  done <<< "${mappings}"

  # Supporting documents placeholders
  seed_supporting_placeholders

  # Generate a draft manifest (optional)
  generate_manifest

  info "Alignment completed."
  info "Summary written to: ${ALIGN_SUMMARY}"
  info "Log written to: ${ALIGN_LOG}"
  info "Container root: ${TARGET_DIR}"
  info "Next step: Package as ASiC-E (ZIP) ensuring 'mimetype' is stored with no compression, then sign with XAdES-LTA."
}

main "$@"
